project_id = "ezssdagxqsemhgvabhyk"

[functions.chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.code-assistant]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.check-video-status]
verify_jwt = false